# Generated by Django 5.1.5 on 2025-01-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SideMeal',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cuisine', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('calories_per_serving', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meal/main-meal/%Y/%m/%d/')),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('tags', models.ManyToManyField(to='meal.tag')),
            ],
        ),
        migrations.CreateModel(
            name='MainMeal',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cuisine', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('calories_per_serving', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meal/main-meal/%Y/%m/%d/')),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('tags', models.ManyToManyField(to='meal.tag')),
            ],
        ),
    ]
